name: Build OpenAppFilter for PVE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # 1. 拉取 OpenWrt 源码
      - name: Checkout OpenWrt source
        uses: actions/checkout@v4
        with:
          repository: immortalwrt/immortalwrt  # 替换为你的 ImmortalWrt 仓库
          submodules: recursive

      # 2. 下载 OpenAppFilter
      - name: Download OpenAppFilter
        run: |
          git clone https://github.com/destan19/OpenAppFilter.git package/OpenAppFilter

      # 3. 动态获取 PVE 内核版本并下载头文件
      - name: Fetch PVE kernel headers
        run: |
          wget http://download.proxmox.com/debian/pve/dists/bookworm/pve-no-subscription/binary-amd64/proxmox-default-kernel_1.1.0_all.deb
          apt install -y ./proxmox-default-kernel_1.1.0_all.deb
          wget http://download.proxmox.com/debian/pve/dists/bookworm/pve-no-subscription/binary-amd64/pve-headers_8.4.0_all.deb
          sudo apt install -y ./pve-headers_8.4.0_all.deb

      # 4. 配置编译环境（关键步骤）
      - name: Configure environment
        run: |
          # 使用 PVE 内核路径替换 OpenWrt 默认内核路径
          echo "CONFIG_EXTERNAL_KERNEL_TREE=/usr/src/linux-headers-$(uname -r)" >> .config
          echo "CONFIG_PACKAGE_luci-app-oaf=y" >> .config
          echo "CONFIG_PACKAGE_open-app-filter=y" >> .config
          echo "CONFIG_PACKAGE_oaf=y" >> .config
          make defconfig

      # 5. 安装编译依赖
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libelf-dev libssl-dev flex bison

      # 6. 编译 OpenAppFilter（强制使用 PVE 内核）
      - name: Compile with PVE kernel
        run: |
          make package/OpenAppFilter/oaf/compile \
            KERNEL_DIR=/usr/src/linux-headers-$(uname -r) \
            ARCH=x86_64 \
            V=s

      # 7. 上传生成的模块和 IPK
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pve-openappfilter
          path: |
            bin/packages/**/oaf*.ipk
            package/OpenAppFilter/oaf/src/*.ko  # 内核模块
