name: Build OpenAppFilter for OpenWrt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04  # 推荐使用更新的系统版本
    steps:
      - name: Checkout OpenWrt source
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt  # 替换为你的仓库
          submodules: recursive
          fetch-depth: 0  # 确保拉取完整历史记录（某些插件需要）

      - name: Download OpenAppFilter
        run: |
          git clone https://github.com/destan19/OpenAppFilter.git package/OpenAppFilter

      - name: Enable OpenAppFilter in config
        run: |
          echo "CONFIG_PACKAGE_luci-app-oaf=y" >> .config
          make defconfig

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses-dev unzip zstd python3

      # 缓存加速编译（关键优化）
      - name: Cache OpenWrt downloads
        uses: actions/cache@v3
        with:
          path: |
            dl
            tmp
          key: ${{ runner.os }}-openwrt-${{ hashFiles('feeds.conf.default') }}

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      # 编译插件（选择性编译）
      - name: Compile OpenAppFilter
        run: |
          make package/OpenAppFilter/{luci-app-oaf,open-app-filter,oaf}/compile V=s

      # 使用 v4 版本的 upload-artifact
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openappfilter-packages
          path: |
            bin/packages/**/oaf*.ipk
            bin/packages/**/luci-app-oaf*.ipk
            bin/packages/**/open-app-filter*.ipk
          retention-days: 7  # 自动清理旧文件
